### ISSUE TITLE
Cannot compile on Linux since 1.9.0

### ISSUE THREAD

**Issue by balazskiss** [SwiftyBeaver/SwiftyBeaver#392]
SwiftyBeaver/Sources/FileDestination.swift:135:27: error: use of unresolved identifier 'NSFileCoordinator'

**Comment by skreutzberger** [comment]
What Swift version are you using?

**Comment by balazskiss** [comment]
5.0.2

**Comment by skreutzberger** [comment]
can you please try to update to the latest Swift version?

**Comment by sanvean** [comment]
Hi, 

Having the same issue using Docker image swift-5.1.4-xenial . Switched to latest swift-5.2.1-xenial as advised but it's still not compiling with the same error as above.

Both these Linux Swift versions are compiling 1.8.4 without issue if that helps!

Thanks

**Comment by skreutzberger** [comment]
Thanks! We will investigate it further. So far no one else is experiencing issues and our Linux integration tests work well so I close the ticket for now.

**Comment by tomattoz** [comment]
Hi @skreutzberger !

Not sure why your tests works well. It looks like NSFileCoordinator is not implemented on Linux (not refs in https://github.com/apple/swift-corelibs-foundation).

The only on mention of NSFileCoordination in context of Linux I've found is https://forums.swift.org/t/pitch-move-urlsession-to-new-foundationnetworking-module/14002/17.

I have the same error on Docker with Ubuntu 18.04.5, swift 5.0, 5.1, 5.2.

Could you please look more attentively to this issue?

**Comment by mohok** [comment]
It is still not working. Any solutions?

**Comment by sanvean** [comment]
I've just linked against 1.8.4 for the time being. Maybe re-open an issue if you need access to features in the later versions? I don't think this has gotten any further attention since it was closed in April.

Really not sure how SwiftyBeaver's Linux tests for versions > 1.8.4 are working atm as per @tomattoz 's comments.

**Comment by mohok** [comment]
It's bad news. I should link that version too. Thank you @sanvean .

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED.
