### ISSUE TITLE
1.4.3 does not compile with swift 3.1

### ISSUE THREAD

**Issue by sportlabsMike** [SwiftyBeaver/SwiftyBeaver#267]
Various errors to do with String beginning with:

.../.build/checkouts/SwiftyBeaver.git--1637639271898239920/Sources/AES256CBC.swift:36:37: error: 'count' is unavailable: there is no universally good answer, see the documentation comment for discussion
        if !str.isEmpty && password.count == 32 {
                                    ^~~~~
Swift.String:231:16: note: 'count' has been explicitly marked unavailable here
    public var count: Int { get }
               ^

**Comment by sportlabsMike** [comment]
Note: this is with xcode8.3 / swift 3.1

**Comment by skreutzberger** [comment]
Please use SwiftyBeaver 1.4.2 or upgrade your codebase to Swift 3.2. Thanks!

**Comment by sportlabsMike** [comment]
OK, thanks.
